apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: product-service
  labels:
    component: product-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      component: product-service   
  template:
    metadata:
      labels: # labels to select/identify the deployment
        component: product-service  
    spec:     # pod spec               
      containers: 
      - name: product-service
        image: quay.io/jason_mimick/product-service # image we pushed
        ports:
        - containerPort: 80
        env:
          - name: PRODUCT_SERVICE_DB
            valueFrom:
              secretKeyRef:
               name: product-service-db
               key: dburi
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    component: product-service
spec:
  selector:
    component: product-service
  ports:
  - name: http
    targetPort: 80
    port: 80

