---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: products-service
  namespace: mongodb
  labels:
    component: products-service
spec:
  replicas: 2
  selector:
    matchLabels:
      component: products-service   
  template:
    metadata:
      labels: # labels to select/identify the deployment
        component: products-service  
    spec:     # pod spec               
      containers: 
      - name: products-service
        image: quay.io/jason_mimick/products-service # image we pushed
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    component: products-service
  namespace: mongodb
spec:
  selector:
    component: products-service
  ports:
  - name: http
    targetPort: 5000
    port: 80
